services:
  - type: web
    name: my-lms-backend
    runtime: docker
    dockerContext: .
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: APP_PROFILE
        value: mysql
      - key: MYSQL_URL
        sync: false
      - key: MYSQL_USER
        sync: false
      - key: MYSQL_PASSWORD
        sync: false
      - key: APP_CORS_ALLOWED_ORIGIN_PATTERNS
        value: https://kluniversityeducationlms.netlify.app,https://*.netlify.app
      - key: JWT_SECRET
        sync: false
